dist: bionic
sudo: required
language: java
jdk: openjdk11
before_install:
- sudo apt-get -y install libpng16-16 libwebkit2gtk-4.0-37 zlib1g-dev libc6-dev libstdc++6
- sudo apt-get -y install python3-pip python-dev
- sudo apt-get -y install wget
- DEBIAN_FRONTEND=noninteractive sudo apt-get -y install xorg xserver-xorg-video-dummy
- sudo -H pip3 install -U setuptools
- sudo -H pip3 install -U wheel
- python3 -V
- pip3 -V
install:
- pip3 install gdown
- pip3 install mbpkg
script:
- "./travis.sh"
